CREATE TABLE IF NOT EXISTS "CHANNEL" ("_id" INTEGER PRIMARY KEY NOT NULL, "CHANNEL_TITLE" TEXT NOT NULL UNIQUE, "CATEGORY" TEXT, "SUMMARY" TEXT, "URL" TEXT, "NEW_ITEM_COUNT" INTEGER);
CREATE TABLE IF NOT EXISTS "IMAGE" ("_id" INTEGER PRIMARY KEY NOT NULL, "IMAGE_CHANNEL" TEXT NOT NULL, "TITLE" TEXT, "IMAGE_URL" TEXT UNIQUE, "LINK" TEXT, "WIDTH" INTEGER, "HEIGHT" INTEGER);
CREATE TABLE IF NOT EXISTS "ITEM" ("_id" INTEGER PRIMARY KEY NOT NULL, "ITEM_CHANNEL" TEXT NOT NULL, "TITLE" TEXT, "PUBDATE" LONG, "DURATION" TEXT, "AUDIO_URL" TEXT, "AUDIO_TYPE" TEXT, "LINK" TEXT, "HERO_IMAGE" TEXT, "SUBTITLE" TEXT, "SUMMARY" TEXT, "UNIQUEID" TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "PLAYLIST" ("_id" INTEGER PRIMARY KEY NOT NULL, "ITEM_PLAYLIST" INTEGER NOT NULL UNIQUE, "LIST_POSITION" INTEGER);
CREATE TABLE IF NOT EXISTS "ITEM_PLAY" ("_id" INTEGER PRIMARY KEY NOT NULL, "ITEM_ID" INTEGER NOT NULL UNIQUE, "DOWNLOADED" INTEGER, "DOWNLOAD_ID" LONG, "PLAY_POSITION" INTEGER, "MAX_DURATION" INTEGER);

CREATE VIEW IF NOT EXISTS "FULL_CHANNEL" AS SELECT * FROM CHANNEL LEFT OUTER JOIN IMAGE ON CHANNEL.CHANNEL_TITLE = IMAGE.IMAGE_CHANNEL;
CREATE VIEW IF NOT EXISTS "FULL_ITEM" AS SELECT * FROM ITEM LEFT OUTER JOIN IMAGE ON ITEM.ITEM_CHANNEL = IMAGE.IMAGE_CHANNEL LEFT OUTER JOIN PLAYLIST ON ITEM._id = PLAYLIST.ITEM_PLAYLIST LEFT OUTER JOIN CHANNEL ON ITEM.ITEM_CHANNEL = CHANNEL.CHANNEL_TITLE LEFT OUTER JOIN ITEM_PLAY ON ITEM._id = ITEM_PLAY.ITEM_ID;
CREATE VIEW IF NOT EXISTS "PLAYLIST_ITEM" AS SELECT * FROM PLAYLIST, ITEM WHERE ITEM_PLAYLIST = ITEM._id;
