CREATE TABLE IF NOT EXISTS "CHANNEL" ("_id" INTEGER PRIMARY KEY NOT NULL, "TITLE" TEXT NOT NULL UNIQUE, "CATEGORY" TEXT, "SUMMARY" TEXT);
CREATE TABLE IF NOT EXISTS "IMAGE" ("_id" INTEGER PRIMARY KEY NOT NULL, "CHANNEL" TEXT NOT NULL, "TITLE" TEXT, "URL" TEXT, "LINK" TEXT, "WIDTH" INTEGER, "HEIGHT" INTEGER);
CREATE TABLE IF NOT EXISTS "ITEM" ("_id" INTEGER PRIMARY KEY NOT NULL, "CHANNEL" TEXT NOT NULL, "TITLE" TEXT, "PUBDATE" TEXT, "AUDIO_URL" TEXT, "AUDIO_TYPE" TEXT, "LINK" TEXT, "SUBTITLE" TEXT, "SUMMARY" TEXT);

CREATE TABLE IF NOT EXISTS "PLAYLIST" ("_id" INTEGER PRIMARY KEY NOT NULL, "ITEM_ID" INTEGER NOT NULL UNIQUE, DOWNLOADED INTEGER);

CREATE VIEW IF NOT EXISTS "FULL_CHANNEL" AS SELECT * FROM CHANNEL LEFT OUTER JOIN IMAGE ON CHANNEL.TITLE = IMAGE.CHANNEL;
CREATE VIEW IF NOT EXISTS "PLAYLIST_ITEM" AS SELECT * FROM PLAYLIST, ITEM WHERE ITEM_ID = ITEM._id;